### PR TITLE
Remove multicast_subscribe functionality from endpoint

### PR DESCRIPTION
**Pull request by james-smith-za**
This removes the dependency on `netifaces`.

That's good. One less thing.

### CODE REVIEW

**Comment by james-smith-za** [comment]
@ludwigschwardt I am under the impression that you control releases of katsdptelstate. Would you be able to cut a new one for us?

**Review by bmerry — APPROVED** [review]
LGTM

**Comment by ludwigschwardt** [comment]
For the record, here is a timeline of what happened:

- Dec 2013: @simonr adds multicast support to ingest
- Feb 2015: @bmerry creates the `Endpoint` class with `multicast_subscribe`
- Feb 2015: @bmerry moves `Endpoint` to `katsdptelstate`
- Mar 2016: @bmerry switches CBF ingest to use `spead2` multicast support instead
- Mar 2017: @bmerry deletes the last bit of cam2spead

After that, no-one calls `multicast_subscribe` anymore, so this looks safe 😂

**Comment by ludwigschwardt** [comment]
I'll cook up a release (hopefully by Thursday - I'm on site tomorrow).

**Pull request merged**
